### ISSUE TITLE
Categorize the blog posts

### ISSUE THREAD

**Issue by ApolloBian** [Hansimov/Hansimov.github.io#2]
It will be nice if blog posts can be organized into different categories.

**Comment by Hansimov** [comment]
@ApolloBian 
You can click `More` on the sidebar (`Recent` by default) and select `Tags`, then all tags will be displayed.
Click any tag you are interested in and a list of the posts (well, we call them 'tiddlers' in Tiddlywiki) under this tag will be shown.

BTW, it is not always the best method to classify posts or notes to some specified categories, since the structure of knowledge and ideas might not be tree-like but net-like. Thus, I organize these tiddlers by tags instead of categories.

Here is the [**Philosophy of Tiddlers**](https://tiddlywiki.com/static/Philosophy%2520of%2520Tiddlers.html):
> The purpose of recording and organising information is so that it can be used again. The value of recorded information is directly proportional to the ease with which it can be re-used.
> 
> The philosophy of tiddlers is that we maximise the possibilities for re-use by slicing information up into the smallest semantically meaningful units with rich modelling of relationships between them. Then we use aggregation and composition to weave the fragments together to present narrative stories.
> 
> TiddlyWiki aspires to provide an algebra for tiddlers, a concise way of expressing and exploring the relationships between items of information.

That is why we call it 'wiki' instead of 'blog'.
